import type { CardDef, CardInst, CardNumbers, Rarity } from "./types";
import type { ClassId } from "./characters";
import type { Rng } from "./rng";

export const CARDS: CardDef[] = [
  {
    id: "strike",
    name: "Strike",
    type: "attack",
    rarity: "starter",
    cost: 1,
    target: "enemy",
    text: (n) => `Deal ${n.damage} damage.`,
    numbers: (up) => ({ damage: up ? 9 : 6 }),
  },
  {
    id: "guard",
    name: "Guard",
    type: "skill",
    rarity: "starter",
    cost: 1,
    target: "self",
    text: (n) => `Gain ${n.block} Block.`,
    numbers: (up) => ({ block: up ? 9 : 6 }),
  },
  {
    id: "brand",
    name: "Brand",
    type: "attack",
    rarity: "starter",
    cost: 2,
    target: "enemy",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.vulnerable} Vulnerable.`,
    numbers: (up) => ({ damage: up ? 10 : 8, vulnerable: up ? 3 : 2 }),
  },
  {
    id: "dirge",
    name: "Dirge",
    type: "attack",
    rarity: "starter",
    cost: 1,
    target: "enemy",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.weak} Weak.`,
    numbers: (up) => ({ damage: up ? 6 : 4, weak: up ? 2 : 1 }),
  },
  {
    id: "fade",
    name: "Fade",
    type: "skill",
    rarity: "starter",
    cost: 1,
    target: "self",
    special: "acrobatics",
    text: (n) => `Gain ${n.block} Block. Discard a random card.`,
    numbers: (up) => ({ block: up ? 12 : 9 }),
  },
  {
    id: "ember",
    name: "Ember",
    type: "skill",
    rarity: "starter",
    cost: 1,
    target: "self",
    summon: "ember",
    classId: "kindled",
    text: (n) =>
      n.stageBonus
        ? "Call Ember at II. Play again to Evolve (max III). At III, Call again to Surge."
        : "Call Ember. Play again to Evolve (I→II→III). At III, Call again to Surge.",
    numbers: (up) => (up ? { stageBonus: 1 } : {}),
  },
  {
    id: "rime",
    name: "Rime",
    type: "skill",
    rarity: "starter",
    cost: 1,
    target: "self",
    summon: "rime",
    classId: "kindled",
    text: (n) =>
      n.stageBonus
        ? "Call Rime at II. Play again to Evolve (max III). At III, Call again to Surge."
        : "Call Rime. Play again to Evolve (I→II→III). At III, Call again to Surge.",
    numbers: (up) => (up ? { stageBonus: 1 } : {}),
  },
  {
    id: "spark",
    name: "Spark",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    summon: "spark",
    classId: "kindled",
    text: (n) =>
      n.stageBonus
        ? "Call Spark at II. Play again to Evolve (max III). At III, Call again to Surge."
        : "Call Spark. Play again to Evolve (I→II→III). At III, Call again to Surge.",
    numbers: (up) => (up ? { stageBonus: 1 } : {}),
  },
  {
    id: "gloom",
    name: "Gloom",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    summon: "gloom",
    classId: "kindled",
    text: (n) =>
      n.stageBonus
        ? "Call Gloom at II. Play again to Evolve (max III). At III, Call again to Surge."
        : "Call Gloom. Play again to Evolve (I→II→III). At III, Call again to Surge.",
    numbers: (up) => (up ? { stageBonus: 1 } : {}),
  },
  {
    id: "unleash",
    name: "Unleash",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    special: "evokeLeft",
    classId: "kindled",
    text: () => "Evoke your leftmost familiar.",
    numbers: (up) => (up ? { energy: 1 } : {}),
  },
  {
    id: "pulse",
    name: "Pulse",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    special: "pulseFamiliars",
    classId: "kindled",
    text: () => "Your familiars pulse.",
    numbers: (up) => (up ? { draw: 1 } : {}),
  },
  {
    id: "feed",
    name: "Feed the Bond",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "evolveAll",
    exhaust: true,
    classId: "kindled",
    text: () => "Evolve each familiar once. Exhaust.",
    numbers: () => ({}),
  },
  {
    id: "twin_call",
    name: "Twin Call",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    summon: "twin",
    classId: "kindled",
    text: (n) =>
      n.stageBonus ? "Call Ember and Rime at stage 2." : "Call Ember and Rime.",
    numbers: (up) => (up ? { stageBonus: 1 } : {}),
  },
  {
    id: "kennel",
    name: "Kennel",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "extraSlot",
    classId: "kindled",
    text: (n) => `Gain ${n.stageBonus ?? 1} familiar slot.`,
    numbers: (up) => ({ stageBonus: up ? 2 : 1 }),
  },
  {
    id: "primeval",
    name: "Primeval Pack",
    type: "skill",
    rarity: "rare",
    cost: 2,
    target: "self",
    summon: "all",
    exhaust: true,
    classId: "kindled",
    text: () => "Call Ember, Rime, Gloom, and Spark. Exhaust.",
    numbers: () => ({}),
  },
  {
    id: "ashen_gift",
    name: "Ashen Gift",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    exhaust: true,
    neutral: true,
    text: (n) => `Draw ${n.draw}. Exhaust.`,
    numbers: (up) => ({ draw: up ? 3 : 2 }),
  },
  {
    id: "pale_coin",
    name: "Pale Coin",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    exhaust: true,
    neutral: true,
    text: (n) => `Gain ${n.gold} gold. Exhaust.`,
    numbers: (up) => ({ gold: up ? 25 : 16 }),
  },
  {
    id: "pall",
    name: "Pall",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    neutral: true,
    text: (n) => `Gain ${n.block} Block. Draw ${n.draw}.`,
    numbers: (up) => ({ block: up ? 12 : 9, draw: 1 }),
  },
  {
    id: "harrow",
    name: "Harrow",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    special: "discardRand",
    neutral: true,
    text: (n) => `Discard a random card. Draw ${n.draw}.`,
    numbers: (up) => ({ draw: up ? 3 : 2 }),
  },
  {
    id: "jester",
    name: "Jester",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    exhaust: true,
    neutral: true,
    text: (n) => `Deal ${n.damage} damage. Exhaust.`,
    numbers: (up) => ({ damage: up ? 12 : 9 }),
  },
  {
    id: "chime",
    name: "Chime",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    exhaust: true,
    neutral: true,
    text: (n) => `Gain ${n.energy} Energy. Exhaust.`,
    numbers: (up) => ({ energy: up ? 2 : 1 }),
  },
  {
    id: "omen",
    name: "Omen",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "all",
    exhaust: true,
    neutral: true,
    text: (n) => `Apply ${n.weak} Weak and ${n.vulnerable} Vulnerable to ALL. Exhaust.`,
    numbers: (up) => ({ weak: up ? 3 : 2, vulnerable: up ? 3 : 2 }),
  },
  {
    id: "reprise",
    name: "Reprise",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "reprise",
    neutral: true,
    text: () => "Put a random card from your discard pile into your hand.",
    numbers: () => ({}),
  },
  {
    id: "last_word",
    name: "Last Word",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    special: "lastWord",
    neutral: true,
    text: (n) => `Deal ${n.damage} damage. If Fatal, gain 2 Energy.`,
    numbers: (up) => ({ damage: up ? 14 : 11 }),
  },
  {
    id: "masquerade",
    name: "Masquerade",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "blockPerAttack",
    neutral: true,
    text: (n) => `Gain ${n.block} Block for each Attack in your hand.`,
    numbers: (up) => ({ block: up ? 7 : 5 }),
  },
  {
    id: "the_toll",
    name: "The Toll",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    neutral: true,
    text: (n) => `Deal ${n.damage} damage ${n.hits} times.`,
    numbers: (up) => ({ damage: up ? 7 : 6, hits: 3 }),
  },
  {
    id: "gild",
    name: "Gild",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    special: "handUpgrade",
    exhaust: true,
    neutral: true,
    text: () => "Upgrade a random card in your hand. Exhaust.",
    numbers: () => ({}),
  },
  {
    id: "burial",
    name: "Burial",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "all",
    exhaust: true,
    neutral: true,
    text: (n) => `Deal ${n.damage} damage to ALL enemies. Exhaust.`,
    numbers: (up) => ({ damage: up ? 22 : 16 }),
  },
  {
    id: "cleave",
    name: "Cleave",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage to ALL enemies.`,
    numbers: (up) => ({ damage: up ? 11 : 8 }),
  },
  {
    id: "twin_cut",
    name: "Twin Cut",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage twice.`,
    numbers: (up) => ({ damage: up ? 6 : 4, hits: 2 }),
  },
  {
    id: "pommel",
    name: "Pommel",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. Draw ${n.draw}.`,
    numbers: (up) => ({ damage: up ? 10 : 9, draw: up ? 2 : 1 }),
  },
  {
    id: "iron_wave",
    name: "Iron Wave",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "interred",
    text: (n) => `Gain ${n.block} Block. Deal ${n.damage} damage.`,
    numbers: (up) => ({ block: up ? 8 : 6, damage: up ? 7 : 5 }),
  },
  {
    id: "heavy",
    name: "Heavy Blow",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage.`,
    numbers: (up) => ({ damage: up ? 18 : 14 }),
  },
  {
    id: "boomerang",
    name: "Bone Fan",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage ${n.hits} times.`,
    numbers: (up) => ({ damage: up ? 4 : 3, hits: 3 }),
  },
  {
    id: "shrug",
    name: "Shrug It Off",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    classId: "interred",
    text: (n) => `Gain ${n.block} Block. Draw 1.`,
    numbers: (up) => ({ block: up ? 12 : 9, draw: 1 }),
  },
  {
    id: "true_grit",
    name: "True Grit",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    special: "trueGrit",
    classId: "interred",
    text: (n) => `Gain ${n.block} Block. Exhaust a random card in your hand.`,
    numbers: (up) => ({ block: up ? 10 : 8 }),
  },
  {
    id: "acrobatics",
    name: "Acrobatics",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "none",
    special: "acrobatics",
    classId: "veil",
    text: (n) => `Draw ${n.draw}. Discard a random card.`,
    numbers: (up) => ({ draw: up ? 4 : 3 }),
  },
  {
    id: "clothesline",
    name: "Clothesline",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.weak} Weak.`,
    numbers: (up) => ({ damage: up ? 14 : 12, weak: 2 }),
  },
  {
    id: "inflame",
    name: "Inflame",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    exhaust: true,
    classId: "interred",
    text: (n) => `Gain ${n.strength} Strength.`,
    numbers: (up) => ({ strength: up ? 3 : 2 }),
  },
  {
    id: "metallicize",
    name: "Metallicize",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    exhaust: true,
    classId: "interred",
    text: (n) => `At the start of your turn, gain ${n.metallicize} Block.`,
    numbers: (up) => ({ metallicize: up ? 4 : 3 }),
  },
  {
    id: "uppercut",
    name: "Uppercut",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.weak} Weak and ${n.vulnerable} Vulnerable.`,
    numbers: (up) => ({
      damage: 13,
      weak: up ? 2 : 1,
      vulnerable: up ? 2 : 1,
    }),
  },
  {
    id: "hemokinesis",
    name: "Hemokinesis",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    special: "hemokinesis",
    classId: "interred",
    text: (n) => `Lose ${n.hpLoss} HP. Deal ${n.damage} damage.`,
    numbers: (up) => ({ hpLoss: 2, damage: up ? 20 : 15 }),
  },
  {
    id: "disarm",
    name: "Disarm",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    special: "disarm",
    exhaust: true,
    classId: "interred",
    text: (n) => `Enemy loses ${Math.abs(n.strength ?? 0)} Strength. Exhaust.`,
    numbers: (up) => ({ strength: up ? -3 : -2 }),
  },
  {
    id: "battle_trance",
    name: "Battle Trance",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "none",
    special: "battleTrance",
    classId: "interred",
    text: (n) => `Draw ${n.draw}. You cannot draw additional cards this turn.`,
    numbers: (up) => ({ draw: up ? 4 : 3 }),
  },
  {
    id: "ghost_armor",
    name: "Ghost Armor",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    ethereal: true,
    classId: "veil",
    text: (n) => `Gain ${n.block} Block. Ethereal.`,
    numbers: (up) => ({ block: up ? 14 : 11 }),
  },
  {
    id: "bloodletting",
    name: "Bloodletting",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    special: "bloodletting",
    classId: "interred",
    text: (n) => `Lose ${n.hpLoss} HP. Gain ${n.energy} Energy.`,
    numbers: (up) => ({ hpLoss: 3, energy: up ? 3 : 2 }),
  },
  {
    id: "dropkick",
    name: "Dropkick",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    special: "dropkick",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. If the enemy is Vulnerable, gain 1 Energy and draw 1.`,
    numbers: (up) => ({ damage: up ? 8 : 5 }),
  },
  {
    id: "shockwave",
    name: "Shockwave",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "all",
    exhaust: true,
    classId: "veil",
    text: (n) => `Apply ${n.weak} Weak to ALL enemies. Exhaust.`,
    numbers: (up) => ({ weak: up ? 5 : 3 }),
  },
  {
    id: "entrench",
    name: "Entrench",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    special: "entrench",
    classId: "interred",
    text: () => "Double your Block.",
    numbers: () => ({}),
  },
  {
    id: "bludgeon",
    name: "Bludgeon",
    type: "attack",
    rarity: "rare",
    cost: 3,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage.`,
    numbers: (up) => ({ damage: up ? 42 : 32 }),
  },
  {
    id: "limit_break",
    name: "Limit Break",
    type: "skill",
    rarity: "rare",
    cost: 1,
    target: "self",
    special: "limitBreak",
    exhaust: true,
    classId: "interred",
    text: () => "Double your Strength.",
    numbers: () => ({}),
  },
  {
    id: "offering",
    name: "Offering",
    type: "skill",
    rarity: "rare",
    cost: 0,
    target: "self",
    special: "offering",
    exhaust: true,
    classId: "interred",
    text: (n) => `Lose ${n.hpLoss} HP. Gain ${n.energy} Energy. Draw ${n.draw}. Exhaust.`,
    numbers: (up) => ({ hpLoss: 6, energy: 2, draw: up ? 5 : 3 }),
  },
  {
    id: "fiend_fire",
    name: "Fiend Fire",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    special: "fiendFire",
    exhaust: true,
    classId: "interred",
    text: (n) =>
      `Exhaust your hand. Deal ${n.damage} damage for each card exhausted. Exhaust.`,
    numbers: (up) => ({ damage: up ? 10 : 7 }),
  },
  {
    id: "impervious",
    name: "Impervious",
    type: "skill",
    rarity: "rare",
    cost: 2,
    target: "self",
    exhaust: true,
    classId: "interred",
    text: (n) => `Gain ${n.block} Block. Exhaust.`,
    numbers: (up) => ({ block: up ? 41 : 31 }),
  },
  {
    id: "immolate",
    name: "Immolate",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "all",
    special: "immolate",
    exhaust: true,
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage to ALL enemies. Add a Wound to your discard. Exhaust.`,
    numbers: (up) => ({ damage: up ? 28 : 21 }),
  },
  {
    id: "maul",
    name: "Maul",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.daze} Daze.`,
    numbers: (up) => ({ damage: up ? 16 : 12, daze: 1 }),
  },
  {
    id: "flail",
    name: "Flail",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage ${n.hits} times.`,
    numbers: (up) => ({ damage: up ? 4 : 3, hits: 3 }),
  },
  {
    id: "execution",
    name: "Execution",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    special: "execute",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. If Fatal, heal ${n.heal}.`,
    numbers: (up) => ({ damage: up ? 20 : 16, heal: 7 }),
  },
  {
    id: "needle",
    name: "Needle",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "veil",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.toxin} Toxin.`,
    numbers: (up) => ({ damage: up ? 5 : 3, toxin: up ? 4 : 3 }),
  },
  {
    id: "nightshade",
    name: "Nightshade",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "veil",
    text: (n) => `Apply ${n.toxin} Toxin.`,
    numbers: (up) => ({ toxin: up ? 7 : 5 }),
  },
  {
    id: "bile",
    name: "Bile",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "all",
    classId: "veil",
    text: (n) => `Apply ${n.toxin} Toxin to ALL enemies.`,
    numbers: (up) => ({ toxin: up ? 4 : 3 }),
  },
  {
    id: "garrote",
    name: "Garrote",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    classId: "veil",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.daze} Daze.`,
    numbers: (up) => ({ damage: up ? 8 : 5, daze: 1 }),
  },
  {
    id: "cloud",
    name: "Moth Cloud",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "all",
    classId: "veil",
    text: (n) => `Apply ${n.toxin} Toxin and ${n.weak} Weak to ALL.`,
    numbers: (up) => ({ toxin: up ? 3 : 2, weak: up ? 2 : 1 }),
  },
  {
    id: "catnap",
    name: "Catnap",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    exhaust: true,
    classId: "veil",
    text: (n) => `Apply ${n.daze} Daze. Exhaust.`,
    numbers: (up) => ({ daze: up ? 2 : 1 }),
  },
  {
    id: "venom",
    name: "Venom",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "envenom",
    classId: "veil",
    text: (n) => `Whenever you play an Attack, apply ${n.toxin} Toxin.`,
    numbers: (up) => ({ toxin: up ? 3 : 2 }),
  },
  {
    id: "draught",
    name: "Draught",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "enemy",
    exhaust: true,
    classId: "veil",
    text: (n) => `Apply ${n.toxin} Toxin. Exhaust.`,
    numbers: (up) => ({ toxin: up ? 6 : 4 }),
  },
  {
    id: "bind",
    name: "Bind",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    classId: "veil",
    text: (n) => `Deal ${n.damage}. Apply ${n.daze} Daze and ${n.toxin} Toxin.`,
    numbers: (up) => ({ damage: up ? 13 : 10, daze: 1, toxin: up ? 5 : 3 }),
  },
  {
    id: "miasma",
    name: "Miasma",
    type: "skill",
    rarity: "rare",
    cost: 2,
    target: "all",
    exhaust: true,
    classId: "veil",
    text: (n) => `Apply ${n.toxin} Toxin to ALL enemies. Exhaust.`,
    numbers: (up) => ({ toxin: up ? 10 : 7 }),
  },
  {
    id: "scorch",
    name: "Scorch",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "kindled",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.cinder} Cinder.`,
    numbers: (up) => ({ damage: up ? 8 : 6, cinder: up ? 4 : 3 }),
  },
  {
    id: "kindle",
    name: "Kindle",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "kindled",
    text: (n) => `Apply ${n.cinder} Cinder.`,
    numbers: (up) => ({ cinder: up ? 7 : 5 }),
  },
  {
    id: "wildfire",
    name: "Wildfire",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "all",
    classId: "kindled",
    text: (n) => `Apply ${n.cinder} Cinder to ALL enemies.`,
    numbers: (up) => ({ cinder: up ? 4 : 3 }),
  },
  {
    id: "afterburn",
    name: "Afterburn",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "afterburn",
    classId: "kindled",
    text: (n) => `At the end of your turn, apply ${n.cinder} Cinder to ALL enemies.`,
    numbers: (up) => ({ cinder: up ? 3 : 2 }),
  },
  {
    id: "cinder_whip",
    name: "Cinder Whip",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    special: "cinderBonus",
    classId: "kindled",
    text: (n) => `Deal ${n.damage} damage. If it has Cinder, deal ${n.damage} again.`,
    numbers: (up) => ({ damage: up ? 10 : 8 }),
  },
  {
    id: "pyre_breath",
    name: "Pyre Breath",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "all",
    classId: "kindled",
    text: (n) => `Deal ${n.damage} to ALL. Apply ${n.cinder} Cinder to ALL.`,
    numbers: (up) => ({ damage: up ? 13 : 10, cinder: 3 }),
  },
  {
    id: "shield_bash",
    name: "Shield Bash",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    special: "shieldBash",
    classId: "interred",
    text: (n) =>
      `Gain ${n.block} Block. If you gained Block this turn, deal ${n.bonus} to a random enemy.`,
    numbers: (up) => ({ block: up ? 8 : 6, bonus: up ? 4 : 3 }),
  },
  {
    id: "rally",
    name: "Rally to the Front",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    classId: "interred",
    text: (n) => `Gain ${n.block} Block. Gain ${n.strength} Strength.`,
    numbers: (up) => ({ block: up ? 15 : 11, strength: up ? 2 : 1 }),
  },
  {
    id: "overhead",
    name: "Overhead Breaker",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    special: "overhead",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. If the target has Weak, deal ${n.bonus} more.`,
    numbers: (up) => ({ damage: up ? 13 : 10, bonus: up ? 8 : 6 }),
  },
  {
    id: "bastion",
    name: "Bastion Protocol",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    special: "bastion",
    classId: "interred",
    text: (n) =>
      `At the start of your turn, gain ${n.metallicize} Block. Whenever you gain Block, gain ${n.bonus} additional Block.`,
    numbers: (up) => ({ metallicize: up ? 3 : 2, bonus: up ? 2 : 1 }),
  },
  {
    id: "groundbreaker",
    name: "Groundbreaker",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    classId: "interred",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.vulnerable} Vulnerable.`,
    numbers: (up) => ({ damage: up ? 10 : 7, vulnerable: up ? 2 : 1 }),
  },
  {
    id: "counterfeit",
    name: "Counterfeit Confidence",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    special: "counterfeit",
    classId: "veil",
    text: (n) =>
      `Draw ${n.draw}. Gain ${n.dexterity} Dexterity. If you have 0 Energy, lose ${n.hpLoss} HP.`,
    numbers: (up) => ({ draw: up ? 2 : 1, dexterity: 1, hpLoss: up ? 2 : 1 }),
  },
  {
    id: "backstep",
    name: "Backstep Whirl",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    special: "backstep",
    classId: "veil",
    text: (n) => `Deal ${n.damage} damage. If you have Block, deal ${n.bonus} more.`,
    numbers: (up) => ({ damage: up ? 8 : 6, bonus: up ? 4 : 3 }),
  },
  {
    id: "coin_flip",
    name: "Coin-Flip Sleight",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    special: "coinFlip",
    classId: "veil",
    text: (n) =>
      `Draw ${n.draw}. Lose ${n.hpLoss} HP. 50%: gain ${n.dexterity} Dexterity.`,
    numbers: (up) => ({ draw: up ? 3 : 2, hpLoss: 1, dexterity: up ? 2 : 1 }),
  },
  {
    id: "vial_dagger",
    name: "Vial Dagger",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    classId: "veil",
    text: (n) => `Deal ${n.damage} damage. Apply ${n.toxin} Toxin.`,
    numbers: (up) => ({ damage: up ? 10 : 8, toxin: up ? 3 : 2 }),
  },
  {
    id: "smoke",
    name: "Smoke & Mirrors",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "smoke",
    classId: "veil",
    text: (n) =>
      `Gain ${n.block} Block. Attacks this turn grant ${n.bonus} Block after they resolve.`,
    numbers: (up) => ({ block: up ? 12 : 9, bonus: up ? 3 : 2 }),
  },
  {
    id: "prism_pulse",
    name: "Prism Pulse",
    type: "power",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    special: "prism",
    classId: "kindled",
    text: (n) =>
      `Gain ${n.focus} Focus. Once per turn, when you play an Attack, deal ${n.plasma} Plasma to a random enemy.`,
    numbers: (up) => ({ focus: up ? 2 : 1, plasma: up ? 6 : 4 }),
  },
  {
    id: "neural_reboot",
    name: "Neural Reboot",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    special: "reboot",
    classId: "kindled",
    text: (n) =>
      `Draw ${n.draw}. If you have no Focus, gain 1 Focus. Otherwise, gain ${n.energy} Energy.`,
    numbers: (up) => ({ draw: up ? 3 : 2, focus: 1, energy: up ? 2 : 1 }),
  },
  {
    id: "voltage",
    name: "Voltage Surge",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    special: "voltage",
    classId: "kindled",
    text: (n) =>
      `Deal ${n.damage} damage. If Fatal, gain ${n.strength} Strength and 1 Focus.`,
    numbers: (up) => ({ damage: up ? 8 : 6, strength: up ? 2 : 1, focus: 1 }),
  },
  {
    id: "channel_spark",
    name: "Channeled Fracture",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    target: "self",
    special: "channelSpark",
    classId: "kindled",
    text: (n) =>
      `Call Spark ${n.stageBonus} times. Deal ${n.bonus} damage to a random enemy.`,
    numbers: (up) => ({ stageBonus: up ? 3 : 2, bonus: up ? 4 : 2 }),
  },
  {
    id: "overheat",
    name: "Overheat Loop",
    type: "power",
    rarity: "rare",
    cost: 3,
    target: "self",
    special: "overheat",
    classId: "kindled",
    text: (n) =>
      `Whenever you play a card, gain ${n.plasma} Plasma. If you play ${n.threshold}+ cards in a turn, deal 12 to a random enemy at end of turn.`,
    numbers: (up) => ({ plasma: up ? 2 : 1, threshold: up ? 2 : 3 }),
  },
  {
    id: "bolt",
    name: "Bolt",
    type: "attack",
    rarity: "starter",
    cost: 1,
    target: "enemy",
    classId: "mage",
    text: (n) => `Deal ${n.damage} damage. Gain ${n.arcana} Arcana.`,
    numbers: (up) => ({ damage: up ? 9 : 6, arcana: 1 }),
  },
  {
    id: "study",
    name: "Study",
    type: "skill",
    rarity: "starter",
    cost: 1,
    target: "self",
    classId: "mage",
    text: (n) => `Draw ${n.draw}. Gain ${n.arcana} Arcana.`,
    numbers: (up) => ({ draw: up ? 2 : 1, arcana: 1 }),
  },
  {
    id: "fireball",
    name: "Fireball",
    type: "attack",
    rarity: "common",
    cost: 2,
    target: "enemy",
    special: "spendArcana",
    classId: "mage",
    text: (n) =>
      `Deal ${n.damage} damage. Gain ${n.arcana} Arcana. If you have 3+ Arcana, spend 3 and deal ${n.bonus} more.`,
    numbers: (up) => ({ damage: up ? 14 : 10, bonus: up ? 16 : 12, arcana: 1 }),
  },
  {
    id: "blizzard",
    name: "Blizzard",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "all",
    classId: "mage",
    text: (n) => `Apply ${n.weak} Weak to ALL. Gain ${n.arcana} Arcana.`,
    numbers: (up) => ({ weak: up ? 2 : 1, arcana: 1 }),
  },
  {
    id: "thunder",
    name: "Thunder",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "enemy",
    special: "thunderArcana",
    classId: "mage",
    text: (n) =>
      `Deal ${n.damage} damage. Gain ${n.arcana} Arcana. If you have 2+ Arcana, gain 1 Energy.`,
    numbers: (up) => ({ damage: up ? 9 : 7, arcana: 1 }),
  },
  {
    id: "ice_lance",
    name: "Ice Lance",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    special: "iceLance",
    classId: "mage",
    text: (n) =>
      `Deal ${n.damage} damage. If you have 2+ Arcana, apply ${n.daze} Daze.`,
    numbers: (up) => ({ damage: up ? 11 : 8, daze: 1 }),
  },
  {
    id: "mana_font",
    name: "Mana Font",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "self",
    exhaust: true,
    classId: "mage",
    text: (n) => `Gain ${n.arcana} Arcana. Exhaust.`,
    numbers: (up) => ({ arcana: up ? 3 : 2 }),
  },
  {
    id: "discharge",
    name: "Discharge",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "all",
    special: "discharge",
    classId: "mage",
    text: (n) => `Deal ${n.damage} damage to ALL for each Arcana. Set Arcana to 0.`,
    numbers: (up) => ({ damage: up ? 7 : 5 }),
  },
  {
    id: "arcane_barrier",
    name: "Arcane Barrier",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    classId: "mage",
    text: (n) => `Gain ${n.block} Block. Gain ${n.arcana} Arcana.`,
    numbers: (up) => ({ block: up ? 12 : 9, arcana: 1 }),
  },
  {
    id: "sage",
    name: "Sage's Boon",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "sage",
    classId: "mage",
    text: () => "Whenever you play a Skill, gain 1 Arcana.",
    numbers: () => ({}),
  },
  {
    id: "meteor",
    name: "Meteor",
    type: "attack",
    rarity: "rare",
    cost: 3,
    target: "all",
    exhaust: true,
    classId: "mage",
    text: (n) => `Deal ${n.damage} to ALL. Gain ${n.arcana} Arcana. Exhaust.`,
    numbers: (up) => ({ damage: up ? 32 : 24, arcana: 2 }),
  },
  {
    id: "bite",
    name: "Bite",
    type: "attack",
    rarity: "starter",
    cost: 1,
    target: "enemy",
    classId: "vampire",
    text: (n) => `Deal ${n.damage} damage. Heal ${n.heal} HP.`,
    numbers: (up) => ({ damage: up ? 8 : 5, heal: up ? 3 : 2 }),
  },
  {
    id: "lash",
    name: "Lash",
    type: "attack",
    rarity: "starter",
    cost: 1,
    target: "enemy",
    classId: "vampire",
    text: (n) => `Lose ${n.hpLoss} HP. Deal ${n.damage} damage.`,
    numbers: (up) => ({ hpLoss: 2, damage: up ? 14 : 10 }),
  },
  {
    id: "drain",
    name: "Drain",
    type: "attack",
    rarity: "common",
    cost: 1,
    target: "all",
    special: "drainAll",
    classId: "vampire",
    text: (n) => `Deal ${n.damage} to ALL. Heal ${n.heal} HP per enemy hit.`,
    numbers: (up) => ({ damage: up ? 6 : 4, heal: 1 }),
  },
  {
    id: "blood_shield",
    name: "Blood Shield",
    type: "skill",
    rarity: "common",
    cost: 1,
    target: "self",
    classId: "vampire",
    text: (n) => `Lose ${n.hpLoss} HP. Gain ${n.block} Block.`,
    numbers: (up) => ({ hpLoss: 3, block: up ? 16 : 12 }),
  },
  {
    id: "sanguine",
    name: "Sanguine Pact",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    target: "self",
    exhaust: true,
    classId: "vampire",
    text: (n) => `Lose ${n.hpLoss} HP. Gain ${n.energy} Energy. Draw ${n.draw}. Exhaust.`,
    numbers: (up) => ({ hpLoss: 4, energy: up ? 3 : 2, draw: 1 }),
  },
  {
    id: "feast",
    name: "Feast",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    special: "feast",
    classId: "vampire",
    text: (n) => `Deal ${n.damage} damage. Heal HP equal to unblocked damage.`,
    numbers: (up) => ({ damage: up ? 13 : 9 }),
  },
  {
    id: "hunger",
    name: "Night's Hunger",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "hunger",
    classId: "vampire",
    text: (n) => `Whenever you play an Attack, heal ${n.heal} HP.`,
    numbers: (up) => ({ heal: up ? 2 : 1 }),
  },
  {
    id: "crimson_tide",
    name: "Crimson Tide",
    type: "attack",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    classId: "vampire",
    text: (n) => `Lose ${n.hpLoss} HP. Deal ${n.damage} damage.`,
    numbers: (up) => ({ hpLoss: 5, damage: up ? 28 : 22 }),
  },
  {
    id: "exsanguinate",
    name: "Exsanguinate",
    type: "attack",
    rarity: "rare",
    cost: 2,
    target: "all",
    special: "drainAll",
    exhaust: true,
    classId: "vampire",
    text: (n) => `Deal ${n.damage} to ALL. Heal ${n.heal} HP per enemy hit. Exhaust.`,
    numbers: (up) => ({ damage: up ? 12 : 8, heal: 2 }),
  },
  {
    id: "blood_tithe",
    name: "Blood Tithe",
    type: "attack",
    rarity: "common",
    cost: 0,
    target: "enemy",
    special: "bloodPrice",
    classId: "vampire",
    text: (n) =>
      `Deal ${n.bonus} damage for each HP spent this turn (${n.damage ?? 0} now).`,
    numbers: (up) => ({ bonus: up ? 6 : 4, damage: 0 }),
  },
  {
    id: "summon_leech",
    name: "Summon Leech",
    type: "power",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    special: "leech",
    classId: "vampire",
    text: (n) =>
      `At the end of your turn, a Leech deals ${n.heal} to a random enemy and heals you ${n.heal}.`,
    numbers: (up) => ({ heal: up ? 3 : 2 }),
  },
  {
    id: "blood_rite",
    name: "Blood Rite",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    target: "self",
    exhaust: true,
    special: "bloodRite",
    classId: "vampire",
    text: (n) =>
      `Lose ${n.hpLoss}–${n.bonus} HP at random. Gain that much Strength. Exhaust.`,
    numbers: (up) => ({ hpLoss: up ? 2 : 1, bonus: up ? 5 : 4 }),
  },
  {
    id: "crimson_requiem",
    name: "Crimson Requiem",
    type: "attack",
    rarity: "rare",
    cost: 3,
    target: "all",
    special: "bloodReckoning",
    classId: "vampire",
    text: (n) =>
      `Heal ${n.heal} HP. Deal damage to ALL equal to HP spent this battle (${n.damage ?? 0} now).`,
    numbers: (up) => ({ heal: up ? 8 : 5, damage: 0 }),
  },
  {
    id: "pale_curse",
    name: "Pale Curse",
    type: "skill",
    rarity: "common",
    cost: 0,
    target: "enemy",
    exhaust: true,
    classId: "vampire",
    text: (n) => `Lose ${n.hpLoss} HP. Apply ${n.vulnerable} Vulnerable. Exhaust.`,
    numbers: (up) => ({ hpLoss: 3, vulnerable: up ? 3 : 2 }),
  },
  {
    id: "wound",
    name: "Wound",
    type: "status",
    rarity: "status",
    cost: 0,
    target: "none",
    unplayable: true,
    text: () => "Unplayable.",
    numbers: () => ({}),
  },
];

export const CARD_BY_ID: Record<string, CardDef> = Object.fromEntries(
  CARDS.map((c) => [c.id, c]),
);

export function defOf(card: CardInst): CardDef {
  const d = CARD_BY_ID[card.defId];
  if (!d) throw new Error(`Unknown card ${card.defId}`);
  return d;
}

export function cardText(card: CardInst, nums?: CardNumbers): string {
  const d = defOf(card);
  const n = nums ?? d.numbers(card.upgraded);
  if (d.id === "limit_break") {
    return `Double your Strength.${card.upgraded ? "" : " Exhaust."}`;
  }
  return d.text(n);
}

export function cardCost(card: CardInst): number {
  const d = defOf(card);
  if (card.upgraded && d.upgradeCost !== undefined) return d.upgradeCost;
  return d.cost;
}

let seq = 1;
export function mintCard(defId: string, upgraded = false, uid?: string): CardInst {
  return { uid: uid ?? `c${seq++}`, defId, upgraded };
}

export function setCardSeq(n: number) {
  seq = n;
}

export function getCardSeq(): number {
  return seq;
}

export function starterDeck(): CardInst[] {
  const d: CardInst[] = [];
  for (let i = 0; i < 5; i++) d.push(mintCard("strike"));
  for (let i = 0; i < 4; i++) d.push(mintCard("guard"));
  d.push(mintCard("brand"));
  return d;
}

export function rollCardRewards(
  rng: Rng,
  bias: "normal" | "elite" | "boss",
  count = 3,
  classId?: ClassId,
): CardInst[] {
  const poolAll = CARDS.filter((c) => {
    if (c.rarity !== "common" && c.rarity !== "uncommon" && c.rarity !== "rare") return false;
    if (c.classId && c.classId !== classId) return false;
    return true;
  });
  const out: CardInst[] = [];
  const used = new Set<string>();
  let guard = 0;
  while (out.length < count && guard++ < 40) {
    const rarity = rollRarity(rng, bias);
    const pool = poolAll.filter((c) => c.rarity === rarity && !used.has(c.id));
    const fallback = poolAll.filter((c) => !used.has(c.id));
    const pick = (pool.length ? pool : fallback)[0]
      ? rng.pick(pool.length ? pool : fallback)
      : null;
    if (!pick) break;
    used.add(pick.id);
    out.push(mintCard(pick.id));
  }
  const nameless = CARDS.filter(
    (c) => c.neutral && (c.rarity === "common" || c.rarity === "uncommon" || c.rarity === "rare") && !used.has(c.id),
  );
  if (out.length && nameless.length && rng.chance(0.32)) {
    const slot = rng.int(0, out.length - 1);
    const rarity = rollRarity(rng, bias);
    const pool = nameless.filter((c) => c.rarity === rarity);
    const pick = rng.pick(pool.length ? pool : nameless);
    out[slot] = mintCard(pick.id);
  }
  return out;
}

function rollRarity(rng: Rng, bias: "normal" | "elite" | "boss"): Rarity {
  const r = rng.next();
  if (bias === "boss") return r < 0.55 ? "rare" : "uncommon";
  if (bias === "elite") {
    if (r < 0.1) return "rare";
    if (r < 0.55) return "uncommon";
    return "common";
  }
  if (r < 0.03) return "rare";
  if (r < 0.4) return "uncommon";
  return "common";
}

export function priceFor(rarity: Rarity, rng: Rng): number {
  if (rarity === "rare") return rng.int(135, 165);
  if (rarity === "uncommon") return rng.int(68, 82);
  return rng.int(45, 55);
}
